### ISSUE TITLE
世界超一流大学.com易主了

### ISSUE THREAD

**Issue by SakuraChanNya** [zsh2517/Shijiedaxue.top#4]
现在指向的应该是广西大学

**Comment by zsh2517** [comment]
收到，已记录。最近两天更新（其实上面很多解析大概都已经过期或者易主了）

**Comment by SakuraChanNya** [comment]
> 收到，已记录。最近两天更新（其实上面很多解析大概都已经过期或者易主了）

话说我申请进划水群没被同意是什么原因呐？我的QQ是129开头372结尾的那个，不知道是不是申请没发送成功

**Comment by zsh2517** [comment]
更新√

以及，邮箱私发了联系方式，重新试一下？
